<?php
require_once 'Hello.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-07 at 21:30:51.
 */
class HelloTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Hello
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Hello;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Hello::getMessage
     */
	public function testGetMessage()
	{
	    $this->assertEquals("hello world", $this->object->getMessage());
	}

    /**
     * @covers Hello::moreMessage
     */
    public function testMoreMessage()
    {
    	$name = "tomoko";
    	$this->assertEquals("Hello, ". $name, $this->object->moreMessage($name));
    }
}
